version: '3'
services:
    app:
        image: 'jftecnologia/frankenphp:8.3'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        tty: true
        env_file:
            - .env
        volumes:
            - '.:/app'
            - './.docker/Caddyfile:/etc/caddy/Caddyfile'
            - './.docker/entrypoint/laravel:/docker-entrypoint.d/laravel'
            - './.docker/laravel-queue.conf:/etc/supervisor/conf.d/laravel-queue.conf'
            - './.docker/laravel-queue-logging.conf:/etc/supervisor/conf.d/laravel-queue-logging.conf'
        networks:
            - sail
        depends_on:
            - mysql
            - mailpit

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        command: ["--max-allowed-packet=1073741824", "--sort-buffer-size=1073741824"]
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
